Fix current Rubocop Issues
shipcloud/billwerk pull request #111
Opened 2022-02-17 16:44 UTC by mortik

Should also fix the following Stories:

[SC-10366](https://app.shortcut.com/shipcloud/story/10366/billwerk-gem-fehlende-frozen-string-literal-kommentare-hinzufügen)

2022-02-22 16:28 UTC, ChristianBreitkreutz commented
**L**ooks**G**ood**T**o**M**e

2022-04-21 09:45 UTC, SteffenHam requested changes
I like having Rubocop as an extra step in the CI 👍

2022-04-21 09:45 UTC, SteffenHam commented on .circleci/config.yml
> +          name: Execute specs
How about a more descriptive name? Something like `Run Rubocop` maybe?

2022-04-21 10:28 UTC, mortik commented on .circleci/config.yml
> +          name: Execute specs
```suggestion
          name: Run Rubocop
```

2022-04-22 09:05 UTC, SteffenHam approved these changes
RTM 👍

2022-04-22 09:16 UTC, merged